# Generated by Django 5.2.6 on 2025-10-21 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BottleBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(max_length=100, unique=True)),
                ("production_date", models.DateField()),
                ("region", models.CharField(max_length=100)),
                ("vintage", models.CharField(max_length=10)),
                ("terroir_data", models.JSONField(default=dict)),
                ("total_bottles", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bottle_id", models.CharField(max_length=100, unique=True)),
                ("qr_code", models.ImageField(blank=True, upload_to="qr_codes/")),
                ("is_registered", models.BooleanField(default=False)),
                ("registration_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registered_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bottles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bottles",
                        to="bottles.bottlebatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BottleScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "bottle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bottles.bottle"
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="bottle",
            index=models.Index(
                fields=["bottle_id"], name="bottles_bot_bottle__f1e822_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bottle",
            index=models.Index(
                fields=["is_registered"], name="bottles_bot_is_regi_f3ec94_idx"
            ),
        ),
    ]
