# Generated by Django 5.2.6 on 2025-10-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bottles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bottle",
            name="bottles_bot_bottle__f1e822_idx",
        ),
        migrations.RemoveIndex(
            model_name="bottle",
            name="bottles_bot_is_regi_f3ec94_idx",
        ),
    ]
