# Generated by Django 5.2.8 on 2025-11-06 16:10

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovementMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_pledges", models.IntegerField(default=0)),
                ("total_rebates", models.IntegerField(default=0)),
                ("community_size", models.IntegerField(default=0)),
                ("impact_stories", models.IntegerField(default=0)),
                ("global_reach", models.JSONField(default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Movement Metrics",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("karma_score", models.FloatField(default=0.0)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Bottle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bottle_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("batch_id", models.CharField(db_index=True, max_length=100)),
                ("production_date", models.DateField()),
                ("terroir_region", models.CharField(default="Chablis", max_length=100)),
                ("terroir_vintage", models.CharField(default="2022", max_length=10)),
                ("registered", models.BooleanField(db_index=True, default=False)),
                ("registration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unregistered", "Unregistered"),
                            ("registered", "Registered"),
                            ("pledged", "Pledged"),
                        ],
                        default="unregistered",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registered_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bottles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-registration_date"],
            },
        ),
        migrations.CreateModel(
            name="CommunityCircle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("focus_areas", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_circles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="community_circles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KarmaPledge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("pledge_text", models.TextField()),
                ("impact_plan", models.TextField()),
                (
                    "impact_type",
                    models.CharField(
                        choices=[
                            ("environmental", "Environmental"),
                            ("community", "Community"),
                            ("education", "Education"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Validation"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_review", "Needs Review"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("ai_validation_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bottle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pledges",
                        to="core.bottle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pledges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("impact", "Impact Report"),
                            ("karma", "Karma Report"),
                            ("community", "Community Report"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(upload_to=core.models.report_pdf_upload_path),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_pledge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="core.karmapledge",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="PledgeValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("approved", models.BooleanField()),
                ("comments", models.TextField(blank=True)),
                ("validator_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("validator_user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="core.karmapledge",
                    ),
                ),
                (
                    "validator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rebate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pledge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebate",
                        to="core.karmapledge",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPDFDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(upload_to=core.models.user_pdf_upload_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engagement_score", models.IntegerField(default=0)),
                ("impact_history", models.JSONField(default=list)),
                ("preferred_causes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-engagement_score"],
            },
        ),
        migrations.AddIndex(
            model_name="bottle",
            index=models.Index(
                fields=["bottle_id"], name="core_bottle_bottle__a3e4af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bottle",
            index=models.Index(
                fields=["batch_id"], name="core_bottle_batch_i_7a95b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bottle",
            index=models.Index(
                fields=["-registration_date"], name="core_bottle_registr_1bef55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bottle",
            index=models.Index(fields=["status"], name="core_bottle_status_789213_idx"),
        ),
        migrations.AddIndex(
            model_name="communitycircle",
            index=models.Index(
                fields=["location"], name="core_commun_locatio_0723b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitycircle",
            index=models.Index(
                fields=["-created_at"], name="core_commun_created_251cfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitycircle",
            index=models.Index(
                fields=["is_active"], name="core_commun_is_acti_f52791_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="karmapledge",
            index=models.Index(
                fields=["-created_at"], name="core_karmap_created_22883c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="karmapledge",
            index=models.Index(fields=["status"], name="core_karmap_status_62c0aa_idx"),
        ),
        migrations.AddIndex(
            model_name="karmapledge",
            index=models.Index(
                fields=["impact_type"], name="core_karmap_impact__58cc7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="karmapledge",
            index=models.Index(fields=["user"], name="core_karmap_user_id_e908b1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="karmapledge",
            unique_together={("user", "bottle")},
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["-generated_at"], name="core_genera_generat_ab37d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["report_type"], name="core_genera_report__cad2ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pledgevalidation",
            index=models.Index(
                fields=["pledge"], name="core_pledge_pledge__feb9e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pledgevalidation",
            index=models.Index(
                fields=["validator"], name="core_pledge_validat_ec4a9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pledgevalidation",
            index=models.Index(
                fields=["created_at"], name="core_pledge_created_44f86a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pledgevalidation",
            unique_together={("pledge", "validator")},
        ),
        migrations.AddIndex(
            model_name="rebate",
            index=models.Index(fields=["status"], name="core_rebate_status_637644_idx"),
        ),
        migrations.AddIndex(
            model_name="rebate",
            index=models.Index(
                fields=["-created_at"], name="core_rebate_created_325264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpdfdocument",
            index=models.Index(
                fields=["-uploaded_at"], name="core_userpd_uploade_62ad78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpdfdocument",
            index=models.Index(
                fields=["is_verified"], name="core_userpd_is_veri_89b216_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["-engagement_score"], name="core_userpr_engagem_91df11_idx"
            ),
        ),
    ]
