# Generated by Django 5.2.5 on 2025-08-28 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pledges', models.IntegerField(default=0)),
                ('total_rebates', models.IntegerField(default=0)),
                ('community_size', models.IntegerField(default=0)),
                ('impact_stories', models.IntegerField(default=0)),
                ('global_reach', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Movement Metrics',
            },
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_id', models.CharField(max_length=100, unique=True)),
                ('batch_id', models.CharField(max_length=100)),
                ('production_date', models.DateField()),
                ('terroir_data', models.JSONField(default=dict)),
                ('registered', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('registered_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_circles', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='community_circles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KarmaPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=100, unique=True)),
                ('pledge_text', models.TextField()),
                ('impact_plan', models.TextField()),
                ('impact_type', models.CharField(choices=[('environmental', 'Environmental'), ('community', 'Community'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], default='pending', max_length=20)),
                ('approvals', models.IntegerField(default=0)),
                ('validations', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rebate_processed', models.BooleanField(default=False)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bottle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karma_score', models.FloatField(default=0.0)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('impact_history', models.JSONField(default=list)),
                ('preferences', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
