# Generated by Django 5.2.6 on 2025-10-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table=None,
        ),
    ]
